import Gaffer
import GafferOSL
import GafferScene
import IECore
import imath

Gaffer.Metadata.registerValue( parent, "serialiser:milestoneVersion", 1, persistent=False )
Gaffer.Metadata.registerValue( parent, "serialiser:majorVersion", 3, persistent=False )
Gaffer.Metadata.registerValue( parent, "serialiser:minorVersion", 3, persistent=False )
Gaffer.Metadata.registerValue( parent, "serialiser:patchVersion", 0, persistent=False )

__children = {}

__children["FrustumCulling"] = Gaffer.Box( "FrustumCulling" )
parent.addChild( __children["FrustumCulling"] )
__children["FrustumCulling"].addChild( Gaffer.StringPlug( "camera", defaultValue = '', flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"].addChild( Gaffer.FloatPlug( "farClip", defaultValue = 10000.0, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"].addChild( Gaffer.FloatPlug( "nearClip", defaultValue = 9.999999747378752e-05, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"].addChild( Gaffer.FloatPlug( "fov", defaultValue = 50.0, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"].addChild( Gaffer.FloatPlug( "overscan", defaultValue = 1.2999999523162842, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"].addChild( Gaffer.FloatPlug( "radius", defaultValue = 0.0, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"].addChild( GafferScene.TransformQuery( "TransformQuery" ) )
__children["FrustumCulling"]["TransformQuery"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"].addChild( GafferScene.ScenePlug( "in", flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"].addChild( GafferOSL.OSLCode( "OSLCode" ) )
__children["FrustumCulling"]["OSLCode"]["parameters"].addChild( Gaffer.V3fPlug( "Point", defaultValue = imath.V3f( 0, 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, interpretation = IECore.GeometricData.Interpretation.Vector ) )
__children["FrustumCulling"]["OSLCode"]["parameters"].addChild( Gaffer.V3fPlug( "Center", defaultValue = imath.V3f( 0, 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, interpretation = IECore.GeometricData.Interpretation.Vector ) )
__children["FrustumCulling"]["OSLCode"]["parameters"].addChild( Gaffer.FloatPlug( "FarClip", defaultValue = 10000.0, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"]["OSLCode"]["parameters"].addChild( Gaffer.FloatPlug( "NearClip", defaultValue = 9.999999747378752e-05, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"]["OSLCode"]["parameters"].addChild( Gaffer.FloatPlug( "Fov", defaultValue = 50.0, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"]["OSLCode"]["parameters"].addChild( Gaffer.FloatPlug( "Overscan", defaultValue = 1.2999999523162842, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"]["OSLCode"]["parameters"].addChild( Gaffer.FloatPlug( "Radius", defaultValue = 0.0, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"]["OSLCode"]["parameters"].addChild( Gaffer.M44fPlug( "CameraMatrix", defaultValue = imath.M44f( 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"]["OSLCode"]["out"].addChild( Gaffer.IntPlug( "DeletePoints", direction = Gaffer.Plug.Direction.Out, defaultValue = 0, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"]["OSLCode"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"].addChild( GafferOSL.OSLObject( "OSLObject" ) )
__children["FrustumCulling"]["OSLObject"]["primitiveVariables"].addChild( Gaffer.NameValuePlug( "customInt", Gaffer.IntPlug( "value", defaultValue = 0, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ), True, "primitiveVariable", Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic ) )
__children["FrustumCulling"]["OSLObject"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"].addChild( GafferOSL.OSLShader( "InPoint" ) )
__children["FrustumCulling"]["InPoint"].loadShader( "ObjectProcessing/InPoint" )
__children["FrustumCulling"]["InPoint"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"].addChild( GafferScene.DeletePoints( "DeletePoints" ) )
__children["FrustumCulling"]["DeletePoints"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"].addChild( Gaffer.BoxIn( "BoxIn" ) )
__children["FrustumCulling"]["BoxIn"].setup( GafferScene.ScenePlug( "out", ) )
__children["FrustumCulling"]["BoxIn"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"].addChild( Gaffer.BoxOut( "BoxOut" ) )
__children["FrustumCulling"]["BoxOut"].setup( GafferScene.ScenePlug( "in", ) )
__children["FrustumCulling"]["BoxOut"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"].addChild( GafferScene.ScenePlug( "out", direction = Gaffer.Plug.Direction.Out, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"].addChild( Gaffer.BoxIn( "BoxIn1" ) )
__children["FrustumCulling"]["BoxIn1"].setup( GafferScene.FilterPlug( "out", defaultValue = 0, minValue = 0, maxValue = 7, ) )
__children["FrustumCulling"]["BoxIn1"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"].addChild( GafferScene.FilterPlug( "filter", defaultValue = 0, minValue = 0, maxValue = 7, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"].addChild( Gaffer.BoolPlug( "enabled", defaultValue = True, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["FrustumCulling"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
Gaffer.Metadata.registerValue( __children["FrustumCulling"], 'noduleLayout:customGadget:addButtonTop:visible', False )
Gaffer.Metadata.registerValue( __children["FrustumCulling"], 'noduleLayout:customGadget:addButtonBottom:visible', False )
Gaffer.Metadata.registerValue( __children["FrustumCulling"], 'noduleLayout:customGadget:addButtonLeft:visible', False )
Gaffer.Metadata.registerValue( __children["FrustumCulling"], 'noduleLayout:customGadget:addButtonRight:visible', False )
Gaffer.Metadata.registerValue( __children["FrustumCulling"]["camera"], 'plugValueWidget:type', 'GafferSceneUI.ScenePathPlugValueWidget' )
Gaffer.Metadata.registerValue( __children["FrustumCulling"]["camera"], 'scenePathPlugValueWidget:scene', 'scene' )
Gaffer.Metadata.registerValue( __children["FrustumCulling"]["camera"], 'nodule:type', '' )
Gaffer.Metadata.registerValue( __children["FrustumCulling"]["farClip"], 'nodule:type', '' )
Gaffer.Metadata.registerValue( __children["FrustumCulling"]["nearClip"], 'nodule:type', '' )
Gaffer.Metadata.registerValue( __children["FrustumCulling"]["fov"], 'nodule:type', '' )
Gaffer.Metadata.registerValue( __children["FrustumCulling"]["overscan"], 'nodule:type', '' )
Gaffer.Metadata.registerValue( __children["FrustumCulling"]["radius"], 'nodule:type', '' )
__children["FrustumCulling"]["TransformQuery"]["scene"].setInput( __children["FrustumCulling"]["BoxIn"]["out"] )
__children["FrustumCulling"]["TransformQuery"]["location"].setInput( __children["FrustumCulling"]["camera"] )
__children["FrustumCulling"]["TransformQuery"]["space"].setValue( 0 )
__children["FrustumCulling"]["TransformQuery"]["__uiPosition"].setValue( imath.V2f( -15.7859154, 4.21369743 ) )
__children["FrustumCulling"]["OSLCode"]["parameters"]["Point"].setInput( __children["FrustumCulling"]["InPoint"]["out"]["value"] )
__children["FrustumCulling"]["OSLCode"]["parameters"]["Center"].setInput( __children["FrustumCulling"]["TransformQuery"]["translate"] )
__children["FrustumCulling"]["OSLCode"]["parameters"]["FarClip"].setInput( __children["FrustumCulling"]["farClip"] )
__children["FrustumCulling"]["OSLCode"]["parameters"]["NearClip"].setInput( __children["FrustumCulling"]["nearClip"] )
__children["FrustumCulling"]["OSLCode"]["parameters"]["Fov"].setInput( __children["FrustumCulling"]["fov"] )
__children["FrustumCulling"]["OSLCode"]["parameters"]["Overscan"].setInput( __children["FrustumCulling"]["overscan"] )
__children["FrustumCulling"]["OSLCode"]["parameters"]["Radius"].setInput( __children["FrustumCulling"]["radius"] )
__children["FrustumCulling"]["OSLCode"]["parameters"]["CameraMatrix"].setInput( __children["FrustumCulling"]["TransformQuery"]["matrix"] )
__children["FrustumCulling"]["OSLCode"]["code"].setValue( 'vector vec = Point - Center;\nvector Cd = -vector(CameraMatrix[2][0], CameraMatrix[2][1], CameraMatrix[2][2]);\n\nfloat vecLen = length(vec);\nfloat radFov = radians(Fov) * 0.5;\n\nif (vecLen > FarClip || vecLen < NearClip) {\n\tDeletePoints = 1;\n} else if ((dot(Cd, vec) / (length(Cd) * vecLen)) <= cos(radFov * Overscan)) {\n\tDeletePoints = 1;\n}\nif (vecLen < Radius && Radius > 0) {\n\tDeletePoints = 0;\n}\n' )
__children["FrustumCulling"]["OSLCode"]["__uiPosition"].setValue( imath.V2f( -3.3309226, -4.86833382 ) )
__children["FrustumCulling"]["OSLObject"]["in"].setInput( __children["FrustumCulling"]["BoxIn"]["out"] )
__children["FrustumCulling"]["OSLObject"]["filter"].setInput( __children["FrustumCulling"]["BoxIn1"]["out"] )
__children["FrustumCulling"]["OSLObject"]["adjustBounds"].setValue( False )
__children["FrustumCulling"]["OSLObject"]["primitiveVariables"]["primitiveVariable"]["name"].setValue( 'deletePoints' )
__children["FrustumCulling"]["OSLObject"]["primitiveVariables"]["primitiveVariable"]["value"].setInput( __children["FrustumCulling"]["OSLCode"]["out"]["DeletePoints"] )
__children["FrustumCulling"]["OSLObject"]["__uiPosition"].setValue( imath.V2f( 10.1169062, 4.34661913 ) )
__children["FrustumCulling"]["InPoint"]["__uiPosition"].setValue( imath.V2f( -27.7468529, -0.668332934 ) )
__children["FrustumCulling"]["DeletePoints"]["in"].setInput( __children["FrustumCulling"]["OSLObject"]["out"] )
__children["FrustumCulling"]["DeletePoints"]["filter"].setInput( __children["FrustumCulling"]["BoxIn1"]["out"] )
__children["FrustumCulling"]["DeletePoints"]["ignoreMissingVariable"].setValue( True )
__children["FrustumCulling"]["DeletePoints"]["__uiPosition"].setValue( imath.V2f( 7.90468311, -3.81744361 ) )
__children["FrustumCulling"]["BoxIn"]["__in"].setInput( __children["FrustumCulling"]["in"] )
Gaffer.Metadata.registerValue( __children["FrustumCulling"]["BoxIn"]["__in"], 'nodule:color', imath.Color3f( 0.240099996, 0.339399993, 0.485000014 ) )
Gaffer.Metadata.registerValue( __children["FrustumCulling"]["BoxIn"]["__in"], 'deletable', True )
Gaffer.Metadata.registerValue( __children["FrustumCulling"]["BoxIn"]["__in"], 'renameable', True )
__children["FrustumCulling"]["BoxIn"]["__uiPosition"].setValue( imath.V2f( 0.246526659, 12.6786499 ) )
__children["FrustumCulling"]["BoxOut"]["in"].setInput( __children["FrustumCulling"]["DeletePoints"]["out"] )
Gaffer.Metadata.registerValue( __children["FrustumCulling"]["BoxOut"]["__out"], 'nodule:color', imath.Color3f( 0.240099996, 0.339399993, 0.485000014 ) )
Gaffer.Metadata.registerValue( __children["FrustumCulling"]["BoxOut"]["__out"], 'nodule:type', 'GafferUI::StandardNodule' )
__children["FrustumCulling"]["BoxOut"]["passThrough"].setInput( __children["FrustumCulling"]["BoxIn"]["out"] )
__children["FrustumCulling"]["BoxOut"]["enabled"].setInput( __children["FrustumCulling"]["enabled"] )
__children["FrustumCulling"]["BoxOut"]["__uiPosition"].setValue( imath.V2f( 5.17559004, -12.1494732 ) )
__children["FrustumCulling"]["out"].setInput( __children["FrustumCulling"]["BoxOut"]["__out"] )
Gaffer.Metadata.registerValue( __children["FrustumCulling"]["out"], 'nodule:type', 'GafferUI::StandardNodule' )
__children["FrustumCulling"]["BoxIn1"]["name"].setValue( 'filter' )
__children["FrustumCulling"]["BoxIn1"]["__in"].setInput( __children["FrustumCulling"]["filter"] )
Gaffer.Metadata.registerValue( __children["FrustumCulling"]["BoxIn1"]["__in"], 'nodule:color', imath.Color3f( 0.689999998, 0.537800014, 0.228300005 ) )
Gaffer.Metadata.registerValue( __children["FrustumCulling"]["BoxIn1"]["__in"], 'nodule:type', 'GafferUI::StandardNodule' )
Gaffer.Metadata.registerValue( __children["FrustumCulling"]["BoxIn1"]["__in"], 'noduleLayout:section', 'right' )
Gaffer.Metadata.registerValue( __children["FrustumCulling"]["BoxIn1"]["__in"], 'plugValueWidget:type', 'GafferSceneUI.FilterPlugValueWidget' )
Gaffer.Metadata.registerValue( __children["FrustumCulling"]["BoxIn1"]["out"], 'noduleLayout:section', 'left' )
__children["FrustumCulling"]["BoxIn1"]["__uiPosition"].setValue( imath.V2f( 23.4124069, 0.264587641 ) )
Gaffer.Metadata.registerValue( __children["FrustumCulling"]["filter"], 'nodule:type', 'GafferUI::StandardNodule' )
Gaffer.Metadata.registerValue( __children["FrustumCulling"]["filter"], 'noduleLayout:section', 'right' )
Gaffer.Metadata.registerValue( __children["FrustumCulling"]["filter"], 'plugValueWidget:type', 'GafferSceneUI.FilterPlugValueWidget' )
Gaffer.Metadata.registerValue( __children["FrustumCulling"]["filter"], 'layout:section', 'Filter' )
__children["FrustumCulling"]["__uiPosition"].setValue( imath.V2f( -5.12730551, -1.00000012 ) )


del __children

